### PR TITLE
Intercepting function calls to avoid unclear changes array

### PR DESCRIPTION
**Pull request by tannerntannern**
Not sure if a PR is the proper way to suggest this feature, but it might give you some ideas on how to resolve the following problem:

**Issue:**
Say you have an array `[1, 10]` that is setup with an observer and that you call `arrProxy.splice(1, 2, 3, 4, 5, 6, 7, 8, 9)`.  The changes array will then be filled with an obnoxious amount of information, detailing which properties have been updated to what.  While it's technically accurate, this does not capture the spirit of what happened, and makes interpreting this information difficult.  Or consider a `push(...)` call; the resulting change details which value changed, but only given the change object, we don't know if the change was the result of `arr[<index>] = <value>` or `arr.push(<value>)`, which may be important to know.  This kind of ambiguity crops up in several other array functions as well.

**A more desirable result:**
In the latter scenario, it would be more desirable if the change object looked something like this: `{type: "function call", "function": "push", "arguments": [<value>], ...}`.  This way, there is no ambiguity about what happened, and the change object is more concise, which could be important for whatever will be processing it.

**A (start to) a potential solution:**
I modified the handler setup slightly so that function calls are intercepted and processed to produce a result like the one I described above.  This, of course breaks, a few tests related to arrays, but I wasn't going to mess with fixing those until I heard your thoughts on this proposal.

### CODE REVIEW

**Comment by ElliotNB** [comment]
You raise a good point about it being an obnoxious level of detail -- I totally agree with that. Unfortunately that's how the `Proxy` object reports changes -- presumably following ECMAScript 2015 spec ( https://www.ecma-international.org/ecma-262/6.0/#sec-proxy-object-internal-methods-and-internal-slots ).

One of the goals of the library is to emulate the behavior of the Proxy object on nested objects, so I'm hesitant to start simplifying how the `Proxy` object reports those changes. A user of the library might need to have the full detail that the `Proxy` object provides by default.

I think it'd be appropriate to leave it up to the user of the library to decide if they want to simplify the output from the library, ignore certain things, etc.

**Comment by tannerntannern** [comment]
My argument is more that even with the high level of detail, it is not trivial (and in some cases, not event possible) to deduce what specifically what happened from the changes alone.  In other words, simplification of the output on the user's part is not really an option if the output is unusable.

I very much appreciate the goal of emulating Proxies for nested objects -- that is the reason I chose to use this library rather than building my own solution from scratch.  However, I believe there has to be some way to address this issue without getting in the way of that goal.  I'm sure that what I proposed is not the best way to do it...

What if the style of change reporting was instead something that could be configured?  Perhaps like pausing observers and changes, one could also choose to have functions reported as their own types of changes as I described in my PR, or have the changes reported in the standard way...  What are your thoughts on this?

**Comment by ElliotNB** [comment]
Yeah, I hear what you're saying, but I think the solution is just going to end up making things too complex and potentially incur a significant performance cost. I'm a big proponent of KISS.

The only way we can reliably determine if `.push` (or any other array mutation method) has been invoked is if we set `Array.push` to a custom wrapper method that internally invokes `Array.prototype.push`. This is basically what I did in `proxy.js` polyfill in order to add support for arrays in ES5 browsers.

Adding those wrapper methods incurs a significant performance cost on large deeply nested objects (with arrays) and it will overwrite any other custom wrapper method that was set beforehand. This was a necessary evil to support arrays in ES5 browsers, but aside from that I don't think it's something we ought to pursue.

**Comment by tannerntannern** [comment]
I respect the commitment to performance.  It looks like I may need to implement my own solution for my use case.  Thank you for entertaining the idea.

**Pull request closed without merging**
