### PR TITLE
Upgrading npm dependencies + Modernizing some legacy code (before 2 other PR)

### PR DESCRIPTION
**Pull request by BrokenSourceCode**
Hi @ElliotNB,

At the beginning, I wanted to create 2 pull requests:
- one to fix the issue https://github.com/ElliotNB/observable-slim/issues/31,
- and another one to improve the `domDelay` option.

But while forking the repository, I realized that all the npm dependencies were old versions and I was having trouble running the Gulp tasks with my latest version of Node.js. So, I decided to update everything and modernize the project a bit!

What i've done:
- Removing the unused npm dependencies.
- Upgrading the npm dependencies.
- Migrating from [istanbul](https://github.com/gotwarlost/istanbul) to [nyc](https://github.com/istanbuljs/nyc) because the first one is no longer maintained and deprecated.
- Rewriting the Gulp tasks in the [`gulpfile.js` ](https://github.com/ElliotNB/observable-slim/blob/30171cc5728a76968468e179856c82561d11c087/gulpfile.js)file.
- Adding a rule in the [`.gitignore`](https://github.com/ElliotNB/observable-slim/blob/30171cc5728a76968468e179856c82561d11c087/.gitignore) file for users such as me who want to easily use custom settings on the [Visual Studio Code](https://code.visualstudio.com/) editor.
- Fixing the quotes in the [`.eslintrc`](https://github.com/ElliotNB/observable-slim/blob/30171cc5728a76968468e179856c82561d11c087/.eslintrc) file: single quotes have been replaced by double quotes.

istanbul

All Gulp commands work perfectly except `gulp coveralls` (a new one created by myself that replaces the npm script with the same name). More specifically, a part of the command below is a problem, maybe because my OS is Windows?

```sh
nyc report --reporter=lcov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

# The part below works.
# nyc report --reporter=lcov

# The part below DOESN'T work.
# && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
```

Hopefully this pull request will be seen, because I really appreciate this little library, and if I could help to improve it, it would be a pleasure for me.

Regards.

### CODE REVIEW

**Comment by ElliotNB** [comment]
@BrokenSourceCode Thank you for the PR -- I appreciate all the effort! I've been meaning to modernize the build and dependencies for a while. I'll get this reviewed shortly.

**Comment by BrokenSourceCode** [comment]
> @BrokenSourceCode Thank you for the PR -- I appreciate all the effort! I've been meaning to modernize the build and dependencies for a while. I'll get this reviewed shortly.

Thank you for answering, I was afraid the project would no longer be maintained! I hope my code will be ok for you when you check it. If you could try to see if the `gulp coveralls` task works for you, I'd appreciate it. I have no idea how the command worked before with [instanbul](https://github.com/gotwarlost/istanbul)...

In the meantime, I will already think about other potential improvements I could suggest. See ya.

**Comment by BrokenSourceCode** [comment]
I finally succeeded to implement the [Windows support for the `gulp coveralls` command](https://github.com/ElliotNB/observable-slim/pull/52/commits/0592eeb22de27c06bbdedabea6f44998a26e7e53).

**Comment by ElliotNB** [comment]
Awesome thank you for the update! I'm a bit swamped at work at the moment, but I'm hoping to get this reviewed by the weekend.

**Review by ElliotNB — APPROVED** [review]
@BrokenSourceCode Looks good to me! Thank you for updating all those dependencies and swapping `istanbul` for `nyc`.

**Comment by ElliotNB** [comment]
@BrokenSourceCode Before you open up the next two PRs, it might be best if I toss in my updates to get Travis CI and Coveralls working again. Travis-ci.org has been replaced with travis-ci.com since this project was last updated. It looks like the unit tests and code coverage stats haven't been run since July 2020.

**Comment by ElliotNB** [comment]
@BrokenSourceCode Scratch that, I'm just going to do it right now ;)

**Comment by BrokenSourceCode** [comment]
> @BrokenSourceCode Looks good to me! Thank you for updating all those dependencies and swapping `istanbul` for `nyc`.

You're welcome. 



> @BrokenSourceCode Before you open up the next two PRs, it might be best if I toss in my updates to get Travis CI and Coveralls working again. Travis-ci.org has been replaced with travis-ci.com since this project was last updated. It looks like the unit tests and code coverage stats haven't been run since July 2020. I'll get that done by this weekend.

When you've updated Travis, could you please let me know if the `gulp coveralls` command actually worked as expected, i.e. as before? This is the only Gulp task I had doubts about when rewriting the `gulpfile.js` file.

I will wait for your an answer before the next 2 PRs I was planning.

**Comment by ElliotNB** [comment]
@BrokenSourceCode Yeah I was having some trouble with getting coveralls to work as expected. Using `gulp` as the task runner was making things more complicated than it need be, so I ripped out most of the `gulp` tasks and put them into `package.json` as `npm` scripts. Just a few minutes ago I put the final touches into `package.json` to get the nyc coverage and coveralls working as expected. I'd recommend pulling over the fresh changes if you haven't already.

Later tonight or tomorrow I'm going to do away with `gulp` entirely and move the build/minify stuff into `package.json` as an npm script. There's no real need for `gulp` anymore.

**Pull request merged**
