### PR TITLE
TypeError: this is not a Date object

### PR DESCRIPTION
**Pull request by reda-alaoui**

### CODE REVIEW

**Comment by ElliotNB** [comment]
Thank you for the PR! 

It looks like you have a linter turned on that diff'ed large portions of the library and test scripts. How difficult would it be for you to undo those extraneous changes?

**Comment by reda-alaoui** [comment]
Hi @ElliotNB ,

Please note that I used gulp lint as recommended in the README.
I remember gulp lint failing without my modifications.
I will undo the linting anyway :)

**Comment by ElliotNB** [comment]
Thanks, I appreciate it! 

The `gulp lint`, at the moment, only checks to verify that the file is indented with tabs instead of spaces. Here's the contents `.eslintrc` file:

```
{
	'parser':'babel-eslint',
	'rules':{
		'indent': ['error', 'tab']
	}
}
```

Tabs for indenting is the only thing that I particularly care about -- anything else I don't particularly have an opinion one way or the other. It looks like you might have an eslint plugin enabled on your IDE that went ahead and auto-corrected the file with some sort of default rule set.

Thanks again for the contribution, this is an important bug fix and I'm looking forward to merging it in and publishing a new minor release shortly.

**Comment by ElliotNB** [comment]
Looks great, thank you for the contribution!

**Comment by reda-alaoui** [comment]
Thank you for this lib ;)

**Comment by reda-alaoui** [comment]
Can you release please?

**Comment by reda-alaoui** [comment]
Thank you :)

**Comment by ElliotNB** [comment]
All published, thanks again for the contributions!

**Pull request merged**
